import cuid from 'cuid'
import { AzureAdUser } from '../../types/generated'
import { RawAzureADUser } from './data'

export default ({
  service,
}: {
  service: RawAzureADUser
  account: string
  region: string
}): AzureAdUser => {
  const {
    id,
    deletedDateTime,
    accountEnabled,
    ageGroup,
    city,
    companyName,
    country,
    createdDateTime,
    creationType,
    department,
    displayName,
    employeeHireDate,
    employeeId,
    employeeType,
    externalUserState,
    externalUserStateChangeDateTime,
    givenName,
    isResourceAccount,
    lastPasswordChangeDateTime,
    mail,
    mailNickname,
    officeLocation,
    onPremisesDistinguishedName,
    onPremisesDomainName,
    onPremisesImmutableId,
    onPremisesLastSyncDateTime,
    onPremisesSyncEnabled,
    onPremisesUserPrincipalName,
    otherMails = [],
    passwordPolicies,
    preferredLanguage,
    proxyAddresses = [],
    state,
    surname,
    usageLocation,
    userPrincipalName,
    userType,
    preferredName,
    responsibilities = [],
    appRoleAssignments = [],
  } = service
  return {
    id: id || cuid(),
    deletedDateTime,
    accountEnabled,
    ageGroup,
    city,
    companyName,
    country,
    createdDateTime,
    creationType,
    department,
    displayName,
    employeeHireDate,
    employeeId,
    employeeType,
    externalUserState,
    externalUserStateChangeDateTime,
    givenName,
    isResourceAccount,
    lastPasswordChangeDateTime,
    mail,
    mailNickname,
    officeLocation,
    onPremisesDistinguishedName,
    onPremisesDomainName,
    onPremisesImmutableId,
    onPremisesLastSyncDateTime,
    onPremisesSyncEnabled,
    onPremisesUserPrincipalName,
    otherMails,
    passwordPolicies,
    preferredLanguage,
    proxyAddresses,
    state,
    surname,
    usageLocation,
    userPrincipalName,
    userType,
    preferredName,
    responsibilities,
    appRoleAssignments: appRoleAssignments.map(aRA => ({ id: cuid(), ...aRA })),
  }
}
