export const regionMap = {
  // Global
  global: 'global',
  // US
  unitedStates: 'unitedstates',
  usEast: 'eastus',
  usEast2: 'eastus2',
  eastUsStage: 'eastusstage',
  eastUs2Stage: 'eastus2stage',
  eastUs2Euap: 'eastus2euap',
  westUs: 'westus',
  westUs2: 'westus2',
  westUs3: 'westus3',
  westUsStage: 'westusstage',
  westUs2Stage: 'westus2stage',
  westCentralUs: 'westcentralus',
  southCentralUs: 'southcentralus',
  southCentralUsStage: 'southcentralusstage',
  centralUs: 'centralus',
  centralUsStage: 'centralusstage',
  centralUsEuap: 'centraluseuap',
  northCentralus: 'northcentralus',
  northCentralUsStage: 'northcentralusstage',
  unitedStatesEuap: 'unitedstateseuap',
  // Canada
  canada: 'canada',
  canadaCentral: 'canadacentral',
  canadaEast: 'canadaeast',
  // Australia
  australia: 'australia',
  australiaEast: 'australiaeast',
  australiaCentral: 'australiacentral',
  australiaCentral2: 'australiacentral2',
  australiaSoutheast: 'australiasoutheast',
  // Asia
  asia: 'asia',
  asiaPacific: 'asiapacific',
  southeastAsia: 'southeastasia',
  eastAsia: 'eastasia',
  eastAsiaStage: 'eastasiastage',
  southeastAsiaStage: 'southeastasiastage',
  singapore: 'singapore',
  // Europe
  europe: 'europe',
  northEurope: 'northeurope',
  westEurope: 'westeurope',
  franceSouth: 'francesouth',
  franceCentral: 'francecentral',
  germanyNorth: 'germanynorth',
  germanyWestCentral: 'germanywestcentral',
  norwayWest: 'norwaywest',
  norwayEast: 'norwayeast',
  switzerlandNorth: 'switzerlandnorth',
  switzerlandWest: 'switzerlandwest',
  polandCentral: 'polandcentral',
  swedenCentral: 'swedenCentral',
  france: 'france',
  germany: 'germany',
  norway: 'norway',
  switzerland: 'switzerland',
  // Uk
  uk: 'uk',
  ukWest: 'ukwest',
  ukSouth: 'uksouth',
  // Africa
  southAfrica: 'southafrica',
  southAfricaWest: 'southafricawest',
  southAfricaNorth: 'southafricanorth',
  // India
  india: 'india',
  westIndia: 'westindia',
  southIndia: 'southindia',
  centralIndia: 'centralindia',
  // Japan
  japan: 'japan',
  japanWest: 'japanwest',
  japanEast: 'japaneast',
  // Korea
  koreaSouth: 'koreasouth',
  koreaCentral: 'koreacentral',
  korea: 'korea',
  // Brazil
  brazil: 'brazil',
  brazilSouth: 'brazilsouth',
  brazilSouthEast: 'brazilsoutheast',
  brazilUs: 'brazilus',
  // UAE
  uaeCentral: 'uaecentral',
  uaeNorth: 'uaenorth',
  uae: 'uae',
  qatarCentral: 'qatarcentral',
}

const {
  // Global
  global,
  // US
  unitedStates,
  usEast,
  usEast2,
  eastUsStage,
  eastUs2Stage,
  eastUs2Euap,
  westUs,
  westUs2,
  westUsStage,
  westUs2Stage,
  westUs3,
  westCentralUs,
  southCentralUs,
  southCentralUsStage,
  centralUs,
  centralUsStage,
  centralUsEuap,
  northCentralus,
  northCentralUsStage,
  unitedStatesEuap,
  // Canada
  canada,
  canadaCentral,
  canadaEast,
  // Australia
  australia,
  australiaEast,
  australiaCentral,
  australiaCentral2,
  australiaSoutheast,
  // Asia
  asia,
  asiaPacific,
  southeastAsia,
  eastAsia,
  eastAsiaStage,
  southeastAsiaStage,
  singapore,
  // Europe
  europe,
  northEurope,
  westEurope,
  franceSouth,
  franceCentral,
  germanyNorth,
  germanyWestCentral,
  norwayWest,
  norwayEast,
  switzerlandNorth,
  switzerlandWest,
  polandCentral,
  swedenCentral,
  france,
  germany,
  norway,
  switzerland,
  // Uk
  uk,
  ukWest,
  ukSouth,
  // Africa
  southAfricaWest,
  southAfricaNorth,
  southAfrica,
  // India
  india,
  westIndia,
  southIndia,
  centralIndia,
  // Japan
  japan,
  japanWest,
  japanEast,
  // Korea
  koreaSouth,
  koreaCentral,
  korea,
  // Brazil
  brazil,
  brazilSouth,
  brazilSouthEast,
  brazilUs,
  // UAE
  uaeCentral,
  uaeNorth,
  uae,
  qatarCentral,
} = regionMap

export default [
  // Global
  global,
  // US
  unitedStates,
  usEast,
  usEast2,
  eastUsStage,
  eastUs2Stage,
  eastUs2Euap,
  westUs,
  westUs2,
  westUsStage,
  westUs2Stage,
  westUs3,
  westCentralUs,
  southCentralUs,
  southCentralUsStage,
  centralUs,
  centralUsStage,
  centralUsEuap,
  northCentralus,
  northCentralUsStage,
  unitedStatesEuap,
  // Canada
  canada,
  canadaCentral,
  canadaEast,
  // Australia
  australia,
  australiaEast,
  australiaCentral,
  australiaCentral2,
  australiaSoutheast,
  // Asia
  asia,
  asiaPacific,
  southeastAsia,
  eastAsia,
  eastAsiaStage,
  southeastAsiaStage,
  singapore,
  // Europe
  europe,
  northEurope,
  westEurope,
  franceSouth,
  franceCentral,
  germanyNorth,
  germanyWestCentral,
  norwayWest,
  norwayEast,
  switzerlandNorth,
  switzerlandWest,
  polandCentral,
  swedenCentral,
  france,
  germany,
  norway,
  switzerland,
  // Uk
  uk,
  ukWest,
  ukSouth,
  // Africa
  southAfricaWest,
  southAfricaNorth,
  southAfrica,
  // India
  india,
  westIndia,
  southIndia,
  centralIndia,
  // Japan
  japan,
  japanWest,
  japanEast,
  // Korea
  koreaSouth,
  koreaCentral,
  korea,
  // Brazil
  brazil,
  brazilSouth,
  brazilSouthEast,
  brazilUs,
  // UAE
  uaeCentral,
  uaeNorth,
  uae,
  qatarCentral,
]
