export default {
  authRoleAssignment: 'authRoleAssignment',
  authRoleDefinition: 'authRoleDefinition',
  disk: 'disk',
  dns: 'dns',
  firewall: 'firewall',
  functionApp: 'functionApp',
  keyVault: 'keyVault',
  networkInterface: 'networkInterface',
  policyAssignment: 'policyAssignment',
  publicIp: 'publicIp',
  resourceGroup: 'resourceGroup',
  securityAssesments: 'securityAssesments',
  securityGroup: 'securityGroup',
  securityPricings: 'securityPricings',
  securitySettings: 'securitySettings',
  storageAccount: 'storageAccount',
  storageContainer: 'storageContainer',
  virtualMachine: 'virtualMachine',
  virtualMachineScaleSet: 'virtualMachineScaleSet',
  virtualNetwork: 'virtualNetwork',
}
