export default {
  disk: 'disk',
  dns: 'dns',
  firewall: 'firewall',
  keyVault: 'keyVault',
  functionApp: 'functionApp',
  networkInterface: 'networkInterface',
  publicIp: 'publicIp',
  resourceGroup: 'resourceGroup',
  securityGroup: 'securityGroup',
  storageAccount: 'storageAccount',
  virtualMachine: 'virtualMachine',
  virtualNetwork: 'virtualNetwork',
  storageContainer: 'storageContainer',
}
