import cuid from 'cuid'
import { AzureAdGroup } from '../../types/generated'
import { RawAzureADGroup } from './data'

export default ({ service }: { service: RawAzureADGroup }): AzureAdGroup => {
  const {
    id,
    deletedDateTime,
    classification,
    createdDateTime,
    description,
    displayName,
    expirationDateTime,
    groupTypes = [],
    isAssignableToRole,
    mail,
    mailEnabled,
    mailNickname,
    membershipRule,
    membershipRuleProcessingState,
    onPremisesDomainName,
    onPremisesLastSyncDateTime,
    onPremisesNetBiosName,
    onPremisesSamAccountName,
    onPremisesSecurityIdentifier,
    onPremisesSyncEnabled,
    preferredDataLocation,
    preferredLanguage,
    proxyAddresses = [],
    renewedDateTime,
    securityEnabled,
    visibility,
    allowExternalSenders,
    isSubscribedByMail,
    isArchived,
    appRoleAssignments = [],
    permissionGrants = [],
    settings = [],
  } = service
  return {
    id: id || cuid(),
    deletedDateTime,
    classification,
    createdDateTime,
    description,
    displayName,
    expirationDateTime,
    groupTypes,
    isAssignableToRole,
    mail,
    mailEnabled,
    mailNickname,
    membershipRule,
    membershipRuleProcessingState,
    onPremisesDomainName,
    onPremisesLastSyncDateTime,
    onPremisesNetBiosName,
    onPremisesSamAccountName,
    onPremisesSecurityIdentifier,
    onPremisesSyncEnabled,
    preferredDataLocation,
    preferredLanguage,
    proxyAddresses,
    renewedDateTime,
    securityEnabled,
    visibility,
    allowExternalSenders,
    isSubscribedByMail,
    isArchived,
    appRoleAssignments: appRoleAssignments.map(aRA => ({ id: cuid(), ...aRA })),
    permissionGrants: permissionGrants.map(pG => ({ id: cuid(), ...pG })),
    settings: settings.map(({ id: sId, values: sValues = [], ...s }) => ({
      id: sId || cuid(),
      values: sValues.map(sValue => ({ id: cuid(), ...sValue })),
      ...s,
    })),
  }
}
